const BCRYPT_SALT_ROUNDS = parseInt(process.env.BCRYPT_SALT_ROUNDS || 12);
const REFRESH_TOKEN_MAX_AGE_MS = 50 * 24 * 60 * 60 * 1000;
const ACCESS_TOKEN_EXPIRES_IN = "15m";
const EMAIL_VERIFICATION_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const VERIFICATION_COOLDOWN_MS = 2 * 60 * 1000;
const PASSWORD_RESET_MAX_AGE_MS = 60 * 60 * 1000;
const MAX_ACTIVE_SESSIONS = 5;
const ACCOUNT_DELETION_MAX_AGE_MS = 60 * 60 * 1000;
const USERNAME_CHANGE_COOLDOWN_MS = 15 * 24 * 60 * 60 * 1000;
const PASSWORD_CHANGE_COOLDOWN_MS = 30 * 24 * 60 * 60 * 1000;
const EMAIL_CHANGE_MAX_AGE_MS = 24 * 60 * 60 * 1000;

module.exports = {
  BCRYPT_SALT_ROUNDS,
  REFRESH_TOKEN_MAX_AGE_MS,
  ACCESS_TOKEN_EXPIRES_IN,
  EMAIL_VERIFICATION_MAX_AGE_MS,
  VERIFICATION_COOLDOWN_MS,
  PASSWORD_RESET_MAX_AGE_MS,
  MAX_ACTIVE_SESSIONS,
  ACCOUNT_DELETION_MAX_AGE_MS,
  USERNAME_CHANGE_COOLDOWN_MS,
  PASSWORD_CHANGE_COOLDOWN_MS,
  EMAIL_CHANGE_MAX_AGE_MS,
};
